#!  python3
# deleteQuizes.py - Delete all quizes generated by randomQuizGenerator.py
# ONLY WORKS ON WINDOWS

import os, re

dir_path = input('Directory to list: ')
directory = os.listdir(dir_path)

regex = re.compile(r'^capitals\w+\.txt$')
files = [('%s\\%s' % 
            (dir_path, file)) for file in directory if regex.search(file)]

if len(files) == 0:
    print("No files found.")
else:
    for file in files:
        print('Removing %s' % file)
        os.remove(file)

input("Press ENTER to quit.")
