#!  python3
# deleteQuizes.py - Delete all quizes generated by randomQuizGenerator.py
# ONLY WORKS ON WINDOWS

import os, re

files = os.listdir(os.getcwd())

regex = re.compile(r'^capitals\w+\.txt$')
files = [file for file in files if regex.search(file)]

if len(files) == 0:
    print("No files found.")
else:
    for file in files:
        print('Removing %s' % file)
        os.remove(file)

input("Press ENTER to quit.")
